### ISSUE TITLE
anaconda python 3.7 issue

### ISSUE THREAD

**Issue by brownto** [fitnr/censusgeocode#13]
I just installed censusgeocode under Python 3.7 using the anaconda prompt with

conda install -c mikesilva censusgeocode

When I import censusgeocode in the spyder environment it is fine (no error). I tried to use the coordinates method
```python
import censusgeocode as cg
c = cg.coordinates(x=-76, y=41)
```
and got the following traceback. Is this a version issue and/or do you have a version than can be run with version 3.7 of python.

Thanks
```
Traceback (most recent call last):
  File "<ipython-input-16-a0886eba4b54>", line 2, in <module>
    c = cg.coordinates(x=-76, y=41)
AttributeError: module 'censusgeocode' has no attribute 'coordinates'
```

**Comment by brownto** [comment]
Just tried with Python 3.6 and got the same error.

**Comment by fitnr** [comment]
I just installed using pip3.7 and can't reproduce. I don't use Anaconda and can't offer support for it.
```python
>>> import censusgeocode as cg
>>> c = cg.coordinates(x=-76, y=41)
>>> c['Census Tracts'][0]['GEOID']
'42079216600'
```

You can try `type(cg)` and `dir(cg)` to see what you're actually working with, I assume that Anaconda has screwed up the import path somehow.

**Comment by brownto** [comment]
Neil,

Thanks for replying. Here is what I get.

**Comment by brownto** [comment]
Neill,

Thanks for replying. Does the following suggest an import path issue?

type(cg)
Out[261]: module

dir(cg)
Out[262]:
['CensusGeocode',
'__builtins__',
'__cached__',
'__doc__',
'__file__',
'__loader__',
'__name__',
'__package__',
'__path__',
'__spec__',
'__version__',
'censusgeocode']

**Comment by fitnr** [comment]
Try doing this
```python
import censusgeocode from censusgeocode as cg
cg.coordinates(x=-76, y=41)
```
