### ISSUE TITLE
Getting Census Tract ID from coordinates (longitude, latitude)

### ISSUE THREAD

**Issue by BishoyKelleny** [fitnr/censusgeocode#18]
I am trying to use the censusgeocode to get the census tract ID (Geoid) from the coordinates of an arbitrary point (x,y), I am using the following code:
```python
censusTractID = int(cg.coordinates(x, y).get('Census Tracts')[0].get('GEOID'))
# For reproduction:
x = -87.6662888874 
y = 41.941555829
censusTractID = int(cg.coordinates(x, y).get('Census Tracts')[0].get('GEOID'))
```
But the code sometimes return the ID of the census tract correctly, and sometimes it just encounters an exception handling error:
```
KeyError: 'CENTLON'
During handling of the above exception, another exception occurred:
and return the following:
ValueError: Unable to parse response from Census
```
And advice on this?

**Comment by amnesiacandres** [comment]
I have observed this problem directly at https://geocoding.geo.census.gov/geocoder/. Sometimes the response throws an error on potions of the response (which sometimes gets corrected if you make the same request again). I believe its not a problem with the library.

**Comment by fitnr** [comment]
I believe that the above diagnosis is correct.
