### ISSUE TITLE
Requests SSL failure

### ISSUE THREAD

**Issue by ryanomatic** [fitnr/censusgeocode#21]
Hello, I'm having issues with SSL failing to work due to a local network issue. I have learned to use the actual API with requests where I put "verify=False" and then it ignores the SSL stuff and works. Can we incorporate 'verify=False' into this code?

**Comment by rynocerus** [comment]
Also, thank you for publishing this - it has been very useful in my learning.

**Comment by fitnr** [comment]
Yes, it would be possible to add a verify option to the code. It would be as simple as adding `verify=False` here: https://github.com/fitnr/censusgeocode/blob/42608f4e9c7d95b73b118e84a746f973269c2dae/censusgeocode/censusgeocode.py#L95

I don't think I would want to make it a default, there's theoretically a reason the API is using HTTPS. But it would be possible to add it as an option in the `CensusGeocode` fetching methods.
