### ISSUE TITLE
Documentation incorrect on default value for vintage and benchmark, non -advanced examples broken

### ISSUE THREAD

**Issue by relishyeah** [fitnr/censusgeocode#23]
Per source code, default values of benchmark and vintage for CensusGeocode object are both None, whereas documentation states "By default, the geocoder uses the "Current" vintage and benchmarks"

```python
import censusgeocode 
cg = censusgeocode.CensusGeocode()
cg.onelineaddress('1600 Pennsylvania Avenue, Washington, DC')

ValueError: Unable to parse response from Census
```

Additionally, most example code returns a "Unable to parse response from Census" Error, like such

```python
import censusgeocode as cg
cg.coordinates(x=-76, y=41)

ValueError: Unable to parse response from Census
```

**Comment by fitnr** [comment]
This is fixed in a new release v0.5.1.

You may find it helpful to review this [github guide to markdown](https://guides.github.com/features/mastering-markdown/).
