### ISSUE TITLE
'module 'censusgeocode' has no attribute 'coordinates' Issue

### ISSUE THREAD

**Issue by gavin-duan** [fitnr/censusgeocode#26]
I tried to install censusgeocode by conda with python version of 3.6 and when I tried the coordinates() function, it shows the error: module 'censusgeocode' has no attribute 'coordinates'. Then I tried to install censusgeocode with pip in a python version of 3.8, while this error came up again. Is there any solution to this error? Thank you.

**Comment by fitnr** [comment]
Can you share the exact code you tried running?

**Comment by gavin-duan** [comment]
Hi, I have solved the issue with reinstall the package with pip again and it works now. Thank you!
