### ISSUE TITLE
Batch Geocode returns a list, not a csv

### ISSUE THREAD

**Issue by ghost** [fitnr/censusgeocode#8]
I've used the addressbatch module before today and always got a csv as a response, as my code was still setup expecting that to be returned. However, today, using addressbatch, I'm getting a list as a response instead. Did this change recently or is it something I'm doing on my end?

**Comment by fitnr** [comment]
According to commit b6f51e6, the addressbatch function has always returned a list. Maybe you used the API directly or used a different module.

**Comment by ghost** [comment]
I see. Well I must have misunderstood the docs then because they state:

"The output will be a CSV file (with a header) and the columns: * id * address * match * matchtype * parsed * tigerlineid * side * lat * lon"

**Comment by fitnr** [comment]
Thanks for pointing out that typo. A pull request would be great if you have a minute to contribute

**Comment by ghost** [comment]
Sure, I'll try to figure out how to do that and submit one.

**Comment by ghost** [comment]
I'm sorry, the explanation of and instructions for a pull request are really confusing. I think it's best if I not be the one to submit one.
