### ISSUE TITLE
Missing error handling when the coordinate response returns a string instead of a float

### ISSUE THREAD

**Issue by ghost** [fitnr/censusgeocode#9]
When using the addressbatch module, I noticed that on occasion the response from the census server will place 'Match' in the 'coordinate' field and then the gps coords will be in the 'statefp' field. Is this a known issue or something possibly on my end with my source file that could be causing a problem?

**Comment by fitnr** [comment]
I haven't seen this. You should raise the issue with the Census.
The goal of this repository is to provide a Python interface for the Census API, not to clean bad data  or paper over upstream bugs.

**Comment by ghost** [comment]
Gotcha, will do. Thanks for your work on this by the way. It's been a great addition to many of the programs I use daily.
